"""empty message

Revision ID: 242e8dca586
Revises: 430ebbed113
Create Date: 2015-04-15 22:17:31.463279

"""

# revision identifiers, used by Alembic.
revision = '242e8dca586'
down_revision = '430ebbed113'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('direction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_of_creation', sa.DateTime(), nullable=False),
    sa.Column('opening_time', sa.DateTime(), nullable=False),
    sa.Column('closing_time', sa.DateTime(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.Column('duration_id', sa.Integer(), nullable=False),
    sa.Column('predictor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['direction_id'], ['direction.id'], ),
    sa.ForeignKeyConstraint(['duration_id'], ['duration.id'], ),
    sa.ForeignKeyConstraint(['predictor_id'], ['predictor.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signal')
    op.drop_table('direction')
    op.drop_table('predictor')
    op.drop_table('duration')
    ### end Alembic commands ###
