"""empty message

Revision ID: 458c4f82e79
Revises: None
Create Date: 2015-04-09 03:24:46.497060

"""

# revision identifiers, used by Alembic.
revision = '458c4f82e79'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.create_table('symbol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # end Alembic commands ###


def downgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.drop_table('symbol')
    # end Alembic commands ###
