"""empty message

Revision ID: 56d72bc16f5
Revises: 458c4f82e79
Create Date: 2015-04-10 00:06:35.354855

"""

# revision identifiers, used by Alembic.
revision = '56d72bc16f5'
down_revision = '458c4f82e79'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('passhash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # end Alembic commands ###


def downgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # end Alembic commands ###
